App\Domain\DTO\ImageDTO:
    properties:
        file:
            - Image:
                maxSize: 2000k
                maxSizeMessage: Image too big (2mo max)
                uploadIniSizeErrorMessage: Image too big (2mo max)
                allowSquare: false
                allowSquareMessage: Please don't use square images
                mimeTypes:
                    - 'image/jpg'
                    - 'image/jpeg'
                    - 'image/png'
                mimeTypesMessage: Only jpg, jpeg and png allowed
                groups:
                    - trickDTO