App\DTO\TrickDTO:
    properties:
        name:
            - NotBlank:
                message: A trick name cannot be ommited
                groups:
                    - trickDTO
            - Length:
                min: 3
                minMessage: The trick name must have at least 3 characters
                max: 140
                maxMessage: The trick name can't have more than 140 characters
                groups:
                    - trickDTO
        description:
            - NotBlank:
                message: A trick description cannot be ommited
                groups:
                    - trickDTO
        imageFeatured:
            - NotBlank:
                message: You must provide one featured image for the trick
                groups:
                    - trickDTO
            - Valid:
                groups:
                    - trickDTO
        images:
            - Valid:
                traverse: true
                groups:
                    - trickDTO
        videos:
            - Valid:
                traverse: true
                groups:
                    - trickDTO
        categories:
            - Count:
                min: 1
                max: 3
                minMessage: You must choose at least one category
                maxMessage: You cannot choose more than {{ limit }} category
                groups:
                    - trickDTO