App\DTO\VideoDTO:
    properties:
        rawUrl:
            - Regex:
                pattern: '#^(http|https)://(www.youtube.com|www.dailymotion.com|vimeo.com)/#'
                match: true
                message: The url must match a valid Youtube, DailyMotion or Vimeo video raw url
                groups:
                    - trickDTO